### ISSUE TITLE
House data seems to be incomplete

### ISSUE THREAD

**Issue by Oi-sin** [mdrenger/GermanHouseCoordinates#4]
The data for houses by postcode are limited to 1000 houses. This has already been mentioned in https://twitter.com/TischnerFlorian/status/1378826002344841220 and can also be found for example in https://raw.githubusercontent.com/mdrenger/GermanHouseCoordinates/main/houses/01129haus.geojson

**Comment by mdrenger** [comment]
similar to #2 , fixed by #3 (22 million house coordinates in https://github.com/mdrenger/GermanHouseCoordinates/tree/main/houses_v2 )

**Comment by Oi-sin** [comment]
Sorry for the duplicate :-/ I didn't see the closed issues.

**Comment by mdrenger** [comment]
@Oi-sin lieber ein duplicate als kein Feedback :)
